### PR TITLE
check in Cabal file; basic GitHub actions

### PR DESCRIPTION
**Pull request by peterbecich**
This allows the project to be built with Cabal. In its current state I think `haskell-server-sdk` cannot be used as a pinned dependency in a `cabal.project`; this error is given: `NoCabalFileFound`
 
Basic GitHub Actions for the Cabal file are provided. Everything works for GHC 8.6, 8.8, and 8.10, but GHC 9.0 fails: https://github.com/peterbecich/haskell-server-sdk/runs/5255432273?check_suite_focus=true

**Requirements**

- [x] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

**Describe the solution you've provided**

Check in `haskell-server-sdk.cabal` generated by Stack from `package.yaml`.

**Describe alternatives you've considered**

**Additional context**

### CODE REVIEW

**Comment by louis-launchdarkly** [comment]
Hello @peterbecich, thank you for your contribution. There are two changes in your PR, and while we are still discussing the Cabal portion of the change, we have decided that we are not going to take the Github Action portion of the change.

LaunchDarkly builds the Haskell SDK through CircleCI, and while this is not visible on the public mirror, there is already a change to test build across different GHC versions. We will keep the build in CircleCI, and make sure we address the 9.0 version correctly.

**Comment by peterbecich** [comment]
Great, thank you @louis-launchdarkly

**Comment by fumieval** [comment]
FYI, lack of .cabal file implies that users of cabal-install are unable to use the package via GitHub (using [source-repository-package](https://cabal.readthedocs.io/en/3.4/cabal-project.html#specifying-packages-from-remote-version-control-locations)). This is problematic when one wants to use an unreleased version of haskell-server-sdk.

**Comment by keelerm84** [comment]
The cabal file is now being committed as of 3.0.3. Sorry it took so long to reach a resolution on this, but I hope this helps going forward.

**Pull request closed without merging**
